### PR TITLE
Removed the -make:transitive argument from pom.xml, which is no longe…

### PR DESCRIPTION
**Pull request by brandon-arnold**
…r compatible with Scala v2.11, fixing issue #8

### CODE REVIEW

**Comment by oozie** [comment]
+1

**Comment by stephan-cr** [comment]
+1

**Comment by davidB** [comment]
thx

**Comment by eprothro** [comment]
Any idea when this will be released? Spent 15 minutes with this issue on a first scala project, as I assume many others have as well. This fix getting released would help those following this tutorial: http://docs.scala-lang.org/tutorials/scala-with-maven.html

**Pull request merged**
