### PR TITLE
Feature/scala 2.12.15

### PR DESCRIPTION
**Pull request by vikas-saxena02**
Upgrading to hopefully promote to new version of archetype. Appreciate any feedback!!

### CODE REVIEW

**Comment by vikas-saxena02** [comment]
@davidB can I please get you to review this and merge it so that we can get a newer version of the archetype

**Comment by slandelle** [comment]
IMO, we'd better sunset/archive this archetype:
* I don't think maven archetypes are still something people use in 2024
* obsolete. Scala 2.12, really? Then what? Scala 2.13 or latest Scala 3?
* too opinionated. Why specs2? Why not scalatest instead? Why not munit instead?

**Comment by vikas-saxena02** [comment]
> IMO, we'd better sunset/archive this archetype:
> 
> * I don't think maven archetypes are still something people use in 2024
> * obsolete. Scala 2.12, really? Then what? Scala 2.13 or latest Scala 3?
> * too opinionated. Why specs2? Why not scalatest instead? Why not munit instead?

Hey mate,

- I don't think maven archetypes are still something people use in 2024
VS: Archetypes are still in use
- obsolete. Scala 2.12, really? Then what? Scala 2.13 or latest Scala 3?
VS: Not relly a lot of Scala based Projects such as Apache Spark are still built on spark 2.12.x
- too opinionated. Why specs2? Why not scalatest instead? Why not munit instead?
VS: I just kept it as it is, will change to scalatest shortly

**Comment by davidB** [comment]
Hi @vikas-saxena02,

I suggest you to fork or create from scratch your maven archetype.

As suggested by @slandelle I'll archive the repository.

Anyway, thanks for your contribution. I created this archetype more than 12 years ago. I'm no longer involved in the scala community and maven-archetype is a pain to test, maintain,... So I'm not able to review the accuracy of your PR and to promote it.

PS: Following my pain with maven-archetype and other tools, I created a tool [ffizer](https://ffizer.github.io/).

**Pull request closed without merging**
